config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  # resource :article

  # get 'exit', to: 'sessions#destroy', as: :logout

  # get 'bungalo/:id', to: 'articles#show', as: :article

  # get '/articles', to: redirect('/articles/1')

  resources :articles do
    resources :comments
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  http_basic_authenticate_with name: "jeffrey", password: "password", except: [:index, :show]

  def index
    @articles = Article.all.reverse
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private
    def article_params
      params.require(:article).permit(:title, :text)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  http_basic_authenticate_with name: "jeffrey", password: "password", only: :destroy

  def show
    @article = Article.find(params[:article_id])
    @comment = Comment.find(params[:id])
  end

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @articles = Article.last(5).reverse
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def logged_in?
    User.exists?(session[:user_id])
  end

  def current_user
    User.find(session[:user_id])
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text, cols: 50, rows: 10 %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/articles/edit.html.erb
<div class="center">
  <h1>Edit article</h1>

  <%= render 'form' %>

  <%= link_to 'Back', articles_path %>
</div>

app/views/articles/index.html.erb
<h1 class="center">All Articles</h1>
  <div class="center"><%= link_to 'New article', new_article_path %></div><br>

  <!-- <ul class="center"> -->
    <% @articles.each do |article | %>
      <div class="center blog-post">
        <h3><%= link_to article.title, article_path(article) %></h3>
          <p class="">Created on <%= article.created_at %>
          <p class=""><%= article.text %></p>
          <%= link_to 'Edit', edit_article_path(article) %> <%= link_to 'Delete', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
      </div><br>
    <% end %>
  <!-- </ul> -->

app/views/articles/new.html.erb
<div class="center">
  <h1>New Article</h1>

  <%= render 'form' %>

  <%= link_to 'Back', articles_path %>
</div>

app/views/articles/show.html.erb
<div class="center">
  <h1>
    <%= @article.title %>
  </h1>
</div>

<div class="center article-text">
  <%= @article.text %>
</div>

<div class="center comment">
  <h2>Comments</h2>
  <%= render @article.comments %>
</div>

<div class="center">
  <h3><small>Add a comment:</small></h3>
  <%= render 'comments/form' %>

  <%= link_to 'Edit', edit_article_path(@article) %> |
  <%= link_to 'Back', articles_path %>
</div>

app/views/comments/_comment.html.erb
<div class="center">
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>

  <p>
    <%= link_to 'Comment-link-1', article_comment_path(@article, comment) %>
  </p>

  <p>
    <%= link_to 'Comment-link-2', url_for([@article, comment]) %>
  </p>

    <p>
    <%= link_to 'Comment-link-3', [@article, comment] %>
  </p>

  <p>
    <%= link_to 'Delete Comment', [comment.article, comment],
                 method: :delete,
                 data: { confirm: 'Are you sure?' } %>
  </p>

</div>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :comment %><br>
    <%= f.text_area :body, cols: 30, rows: 3 %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/comments/show.html.erb
<%= @comment.commenter %><br>
<%= @comment.body %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  </head>

  <body class="background">
    <nav>
      <%= link_to "Home", controller: "welcome" %>
      |
      <%= link_to "All Articles", controller: "articles" %>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1 class="center">Bob Loblaw's Law Blog</h1>
<h2 id="myself" class="center"><small>by Bob Loblaw</small></h2>
  <div class="small-title center"><h2><small>Most recent posts</small></h2></div>
<div class="center">
  <% @articles.each do |article| %>
    <div class="blog-post">
      <h3 class="article-title center"><%= link_to article.title, article_path(article) %></h3>
      <p class="center">Created on <%= article.created_at %>
      <p class="center"><%= article.text %></p>
    </div>
  <% end %>
</div>


<%= link_to "Absolute", articles_url %>
<%= link_to "Relative", articles_path %>